// BitcoinClicker - Hardware Definitions

// Define an array of hardware types as a global variable for use in the main game logic
var hardwareTypes = [
    {
        id: 'recycled_cpu',
        name: 'Recycled CPU',
        description: 'Pulled from a dusty server in a forgotten basement. Barely alive, but still ticking.',
        subcategory: 'CPU',
        baseCost: 10,
        baseHashrate: 1,
        basePower: 15,
        costMultiplier: 1.05,
        unlocked: true
    },
    {
        id: 'celeron_g6900',
        name: 'Celeron G6900',
        description: 'The potato chip. Barely mines, but it’s cheap enough to throw in a junk rig.',
        subcategory: 'CPU',
        baseCost: 45,
        baseHashrate: 3,
        basePower: 40,
        costMultiplier: 1.1,
        unlocked: true
    },
    {
        id: 'pentium_g7400',
        name: 'Pentium Gold G7400',
        description: 'Your trusty CPU. Slow but reliable.',
        subcategory: 'CPU',
        baseCost: 100,
        baseHashrate: 10,
        basePower: 50,
        costMultiplier: 1.15,
        unlocked: true
    },
    {
        id: 'athlon_3000g',
        name: 'Athlon 3000G',
        description: 'The scrappy underdog. Cheap, cheerful, and just enough juice to boot your rig.',
        subcategory: 'CPU',
        baseCost: 150,
        baseHashrate: 15,
        basePower: 55,
        costMultiplier: 1.15,
        unlocked: true
    },
    {
        id: 'apple_m2',
        name: 'Apple M2',
        description: 'Sleek and silent. Optimized for elegance, not brute force.',
        subcategory: 'CPU',
        baseCost: 200,
        baseHashrate: 8,
        basePower: 15,
        costMultiplier: 1.15,
        unlocked: true
    },
    {
        id: 'core_i3_14100',
        name: 'Core i3-14100',
        description: 'The apprentice chip. Learns fast, works hard, but still needs a mentor.',
        subcategory: 'CPU',
        baseCost: 300,
        baseHashrate: 24,
        basePower: 65,
        costMultiplier: 1.2,
        unlocked: false,
        requirement: { totalBTC: 0.05, hashPoints: 0 }
    },
    {
        id: 'ryzen_3_5300g',
        name: 'Ryzen 3 5300G',
        description: 'The jack-of-all-trades. Modest power, built-in graphics, and a heart of silicon gold.',
        subcategory: 'CPU',
        baseCost: 400,
        baseHashrate: 28,
        basePower: 70,
        costMultiplier: 1.2,
        unlocked: false,
        requirement: { totalBTC: 0.1, hashPoints: 0 }
    },
    {
        id: 'apple_m2_pro',
        name: 'Apple M2 Pro',
        description: 'The artist’s muse. Paints pixels with precision, but avoids crypto chaos.',
        subcategory: 'CPU',
        baseCost: 600,
        baseHashrate: 15,
        basePower: 20,
        costMultiplier: 1.2,
        unlocked: false,
        requirement: { totalBTC: 0.15, hashPoints: 0 }
    },
    {
        id: 'core_i5_14400',
        name: 'Core i5-14400',
        description: 'Reliable mercenary. Handles most missions with ease, but not built for mining glory.',
        subcategory: 'CPU',
        baseCost: 800,
        baseHashrate: 35,
        basePower: 90,
        costMultiplier: 1.25,
        unlocked: false,
        requirement: { totalBTC: 0.2, hashPoints: 0 }
    },
    {
        id: 'ryzen_5_7600',
        name: 'Ryzen 5 7600',
        description: 'The silent assassin. Efficient, deadly in short bursts, and good at covert ops.',
        subcategory: 'CPU',
        baseCost: 1000,
        baseHashrate: 40,
        basePower: 85,
        costMultiplier: 1.25,
        unlocked: false,
        requirement: { totalBTC: 0.3, hashPoints: 0 }
    },
    {
        id: 'apple_m3',
        name: 'Apple M3',
        description: 'The philosopher chip. Thinks fast, sips power, and avoids blockchain warfare.',
        subcategory: 'CPU',
        baseCost: 1200,
        baseHashrate: 25,
        basePower: 25,
        costMultiplier: 1.25,
        unlocked: false,
        requirement: { totalBTC: 0.4, hashPoints: 0 }
    },
    {
        id: 'core_i7_14700k',
        name: 'Core i7-14700K',
        description: 'The battlefield general. Commands cores like troops—strong, strategic, and power-hungry.',
        subcategory: 'CPU',
        baseCost: 1500,
        baseHashrate: 55,
        basePower: 120,
        costMultiplier: 1.3,
        unlocked: false,
        requirement: { totalBTC: 0.5, hashPoints: 0 }
    },
    {
        id: 'ryzen_7_7800x3d',
        name: 'Ryzen 7 7800X3D',
        description: 'The gamer’s blade. Sharp, swift, and tuned for frame-perfect strikes.',
        subcategory: 'CPU',
        baseCost: 1800,
        baseHashrate: 85,
        basePower: 110,
        costMultiplier: 1.3,
        unlocked: false,
        requirement: { totalBTC: 0.6, hashPoints: 0 }
    },
    {
        id: 'apple_m3_pro',
        name: 'Apple M3 Pro',
        description: 'The virtuoso. Composes symphonies of code, but won’t touch crypto.',
        subcategory: 'CPU',
        baseCost: 2000,
        baseHashrate: 30,
        basePower: 45,
        costMultiplier: 1.3,
        unlocked: false,
        requirement: { totalBTC: 0.75, hashPoints: 0 }
    },
    {
        id: 'core_i9_14900k',
        name: 'Core i9-14900K',
        description: 'The war machine. Unleashes raw power, but guzzles watts like a mech in overdrive.',
        subcategory: 'CPU',
        baseCost: 2500,
        baseHashrate: 125,
        basePower: 150,
        costMultiplier: 1.35,
        unlocked: false,
        requirement: { totalBTC: 1, hashPoints: 0 }
    },
    {
        id: 'ryzen_9_9950x3d',
        name: 'Ryzen 9 9950X3D',
        description: 'The overlord chip. Dominates games, multitasks like a demigod, and mines with quiet menace.',
        subcategory: 'CPU',
        baseCost: 2800,
        baseHashrate: 250,
        basePower: 140,
        costMultiplier: 1.35,
        unlocked: false,
        requirement: { totalBTC: 1.25, hashPoints: 0 }
    },
    {
        id: 'apple_m3_max',
        name: 'Apple M3 Max',
        description: 'The architect of worlds. Builds empires in silence, but mining? That’s beneath its station.',
        subcategory: 'CPU',
        baseCost: 3000,
        baseHashrate: 50,
        basePower: 50,
        costMultiplier: 1.35,
        unlocked: false,
        requirement: { totalBTC: 1.5, hashPoints: 0 }
    },
    // --- Realistic GPU Models ---
    {
        id: 'gt_740',
        name: 'GT 740',
        description: 'Entry-level 4GB GPU, basic gaming and mining.',
        subcategory: 'GPU',
        baseCost: 58,
        baseHashrate: 12,
        basePower: 50,
        costMultiplier: 1.08,
        unlocked: true
    },
    {
        id: 'gtx_1060_3gb',
        name: 'GTX 1060 3GB',
        description: 'Popular entry-level 3GB GPU, decent for mining.',
        subcategory: 'GPU',
        baseCost: 56,
        baseHashrate: 15,
        basePower: 70,
        costMultiplier: 1.09,
        unlocked: true
    },
    {
        id: 'arc_b570',
        name: 'Arc B570',
        description: 'Budget 10GB Intel GPU, good for gaming and mining.',
        subcategory: 'GPU',
        baseCost: 230,
        baseHashrate: 40,
        basePower: 110,
        costMultiplier: 1.10,
        unlocked: false,
        requirement: { totalBTC: 0.01 }
    },
    {
        id: 'arc_b580',
        name: 'Arc B580',
        description: 'Budget 10GB Intel GPU, slightly better than B570.',
        subcategory: 'GPU',
        baseCost: 250,
        baseHashrate: 45,
        basePower: 120,
        costMultiplier: 1.10,
        unlocked: false,
        requirement: { totalBTC: 0.02 }
    },
    {
        id: 'rtx_5050',
        name: 'RTX 5050',
        description: '8GB budget gaming GPU, entry RTX performance.',
        subcategory: 'GPU',
        baseCost: 240,
        baseHashrate: 48,
        basePower: 120,
        costMultiplier: 1.11,
        unlocked: false,
        requirement: { totalBTC: 0.03 }
    },
    {
        id: 'rx_9060_xt_8gb',
        name: 'RX 9060 XT 8GB',
        description: '8GB AMD GPU, solid budget mining.',
        subcategory: 'GPU',
        baseCost: 270,
        baseHashrate: 52,
        basePower: 125,
        costMultiplier: 1.11,
        unlocked: false,
        requirement: { totalBTC: 0.04 }
    },
    {
        id: 'rtx_5060',
        name: 'RTX 5060',
        description: '8GB mid-range RTX GPU, good for gaming and mining.',
        subcategory: 'GPU',
        baseCost: 289,
        baseHashrate: 60,
        basePower: 130,
        costMultiplier: 1.12,
        unlocked: false,
        requirement: { totalBTC: 0.05 }
    },
    {
        id: 'rtx_5060_ti_8gb',
        name: 'RTX 5060 Ti 8GB',
        description: '8GB Ti version, better mining efficiency.',
        subcategory: 'GPU',
        baseCost: 340,
        baseHashrate: 68,
        basePower: 140,
        costMultiplier: 1.13,
        unlocked: false,
        requirement: { totalBTC: 0.07 }
    },
    {
        id: 'rtx_5060_ti_16gb',
        name: 'RTX 5060 Ti 16GB',
        description: '16GB Ti, high VRAM for better mining.',
        subcategory: 'GPU',
        baseCost: 379,
        baseHashrate: 75,
        basePower: 145,
        costMultiplier: 1.13,
        unlocked: false,
        requirement: { totalBTC: 0.09 }
    },
    {
        id: 'rx_9060_xt_16gb',
        name: 'RX 9060 XT 16GB',
        description: '16GB AMD, mid-range mining and gaming.',
        subcategory: 'GPU',
        baseCost: 350,
        baseHashrate: 72,
        basePower: 150,
        costMultiplier: 1.13,
        unlocked: false,
        requirement: { totalBTC: 0.10 }
    },
    {
        id: 'rx_9070',
        name: 'RX 9070',
        description: '16GB AMD, upper mid-range mining.',
        subcategory: 'GPU',
        baseCost: 600,
        baseHashrate: 110,
        basePower: 180,
        costMultiplier: 1.15,
        unlocked: false,
        requirement: { totalBTC: 0.15 }
    },
    {
        id: 'rx_9070_xt',
        name: 'RX 9070 XT',
        description: '16GB AMD, upper mid-range XT edition.',
        subcategory: 'GPU',
        baseCost: 670,
        baseHashrate: 120,
        basePower: 190,
        costMultiplier: 1.16,
        unlocked: false,
        requirement: { totalBTC: 0.18 }
    },
    {
        id: 'rtx_5070',
        name: 'RTX 5070',
        description: '16GB NVIDIA, upper mid-range RTX.',
        subcategory: 'GPU',
        baseCost: 499,
        baseHashrate: 100,
        basePower: 170,
        costMultiplier: 1.15,
        unlocked: false,
        requirement: { totalBTC: 0.13 }
    },
    {
        id: 'rtx_5070_ti',
        name: 'RTX 5070 Ti',
        description: '16GB high-end gaming GPU, great mining.',
        subcategory: 'GPU',
        baseCost: 749,
        baseHashrate: 140,
        basePower: 210,
        costMultiplier: 1.18,
        unlocked: false,
        requirement: { totalBTC: 0.22 }
    },
    {
        id: 'rtx_5080',
        name: 'RTX 5080',
        description: '16GB high-end RTX, excellent mining.',
        subcategory: 'GPU',
        baseCost: 929,
        baseHashrate: 170,
        basePower: 240,
        costMultiplier: 1.20,
        unlocked: false,
        requirement: { totalBTC: 0.30 }
    },
    {
        id: 'rtx_5090',
        name: 'RTX 5090',
        description: '24GB enthusiast GPU, top mining performance.',
        subcategory: 'GPU',
        baseCost: 2240,
        baseHashrate: 350,
        basePower: 350,
        costMultiplier: 1.25,
        unlocked: false,
        requirement: { totalBTC: 0.5, hashPoints: 10 }
    },
    {
        id: 'tesla_k10',
        name: 'NVIDIA Tesla K10',
        description: 'Legacy 8GB compute GPU, still useful for mining.',
        subcategory: 'GPU',
        baseCost: 59,
        baseHashrate: 18,
        basePower: 90,
        costMultiplier: 1.09,
        unlocked: true
    },
    {
        id: 'rtx_a2000',
        name: 'RTX A2000',
        description: '12GB pro workstation GPU, efficient mining.',
        subcategory: 'GPU',
        baseCost: 850,
        baseHashrate: 120,
        basePower: 110,
        costMultiplier: 1.18,
        unlocked: false,
        requirement: { totalBTC: 0.18, hashPoints: 2 }
    },
    {
        id: 'rtx_a4000',
        name: 'RTX A4000',
        description: '16GB pro workstation GPU, high efficiency.',
        subcategory: 'GPU',
        baseCost: 1050,
        baseHashrate: 140,
        basePower: 130,
        costMultiplier: 1.20,
        unlocked: false,
        requirement: { totalBTC: 0.22, hashPoints: 3 }
    },
    {
        id: 'rtx_a5000',
        name: 'RTX A5000',
        description: '24GB pro workstation GPU, excellent mining.',
        subcategory: 'GPU',
        baseCost: 1800,
        baseHashrate: 200,
        basePower: 180,
        costMultiplier: 1.22,
        unlocked: false,
        requirement: { totalBTC: 0.35, hashPoints: 5 }
    },
    {
        id: 'rtx_a6000',
        name: 'RTX A6000',
        description: '48GB pro workstation GPU, top-tier mining.',
        subcategory: 'GPU',
        baseCost: 3800,
        baseHashrate: 320,
        basePower: 250,
        costMultiplier: 1.25,
        unlocked: false,
        requirement: { totalBTC: 0.6, hashPoints: 8 }
    },
    {
        id: 'rtx_6000_ada',
        name: 'RTX 6000 Ada Gen',
        description: '48GB Ada Lovelace pro GPU, ultimate mining and workstation.',
        subcategory: 'GPU',
        baseCost: 6800,
        baseHashrate: 400,
        basePower: 300,
        costMultiplier: 1.28,
        unlocked: false,
        requirement: { totalBTC: 1.2, hashPoints: 15 }
    },
    {
        id: 'antminer_s9',
        name: 'Antminer S9',
        description: 'Entry-level ASIC, 6.5 TH/s, 1800W. Cheap, but very inefficient.',
        subcategory: 'ASIC',
        baseCost: 1200,
        baseHashrate: 6000,
        basePower: 2000,
        costMultiplier: 1.18,
        unlocked: true
    },
    {
        id: 'antminer_t9p',
        name: 'Antminer T9+',
        description: 'Entry-level ASIC, 5.5 TH/s, 2000W. Cheap, but very inefficient.',
        subcategory: 'ASIC',
        baseCost: 1400,
        baseHashrate: 5000,
        basePower: 2200,
        costMultiplier: 1.18,
        unlocked: true
    },
    {
        id: 'whatsminer_m3',
        name: 'Whatsminer M3',
        description: 'Entry-level ASIC, 7 TH/s, 2200W. Cheap, but very inefficient.',
        subcategory: 'ASIC',
        baseCost: 1300,
        baseHashrate: 6500,
        basePower: 2400,
        costMultiplier: 1.18,
        unlocked: true
    },
    {
        id: 'antminer_s17',
        name: 'Antminer S17',
        description: 'Mid-range ASIC, 50 TH/s, 2700W.',
        subcategory: 'ASIC',
        baseCost: 20000,
        baseHashrate: 50000,
        basePower: 2700,
        costMultiplier: 1.35,
        unlocked: false,
        requirement: { totalBTC: 2.5 }
    },
    {
        id: 'antminer_s17pro',
        name: 'Antminer S17 Pro',
        description: 'Mid-range ASIC, 48 TH/s, 2300W.',
        subcategory: 'ASIC',
        baseCost: 25000,
        baseHashrate: 48000,
        basePower: 2300,
        costMultiplier: 1.38,
        unlocked: false,
        requirement: { totalBTC: 3.0 }
    },
    {
        id: 'whatsminer_m20s',
        name: 'Whatsminer M20S',
        description: 'Mid-range ASIC, 60 TH/s, 3600W.',
        subcategory: 'ASIC',
        baseCost: 35000,
        baseHashrate: 60000,
        basePower: 3600,
        costMultiplier: 1.40,
        unlocked: false,
        requirement: { totalBTC: 4.0 }
    },
    {
        id: 'antminer_t19',
        name: 'Antminer T19',
        description: 'Upper mid-range ASIC, 75 TH/s, 3400W.',
        subcategory: 'ASIC',
        baseCost: 50000,
        baseHashrate: 75000,
        basePower: 3400,
        costMultiplier: 1.42,
        unlocked: false,
        requirement: { totalBTC: 5.0 }
    },
    {
        id: 'whatsminer_m30s',
        name: 'Whatsminer M30S',
        description: 'Upper mid-range ASIC, 78 TH/s, 3600W.',
        subcategory: 'ASIC',
        baseCost: 60000,
        baseHashrate: 78000,
        basePower: 3600,
        costMultiplier: 1.45,
        unlocked: false,
        requirement: { totalBTC: 6.0 }
    },
    {
        id: 'antminer_s19',
        name: 'Antminer S19',
        description: 'High-end ASIC, 85 TH/s, 3700W.',
        subcategory: 'ASIC',
        baseCost: 90000,
        baseHashrate: 85000,
        basePower: 3700,
        costMultiplier: 1.48,
        unlocked: false,
        requirement: { totalBTC: 8.0 }
    },
    {
        id: 'antminer_s19pro',
        name: 'Antminer S19 Pro',
        description: 'High-end ASIC, 100 TH/s, 3700W.',
        subcategory: 'ASIC',
        baseCost: 110000,
        baseHashrate: 100000,
        basePower: 3700,
        costMultiplier: 1.50,
        unlocked: false,
        requirement: { totalBTC: 10.0 }
    },
    {
        id: 'whatsminer_m30spp',
        name: 'Whatsminer M30S++',
        description: 'High-end ASIC, 105 TH/s, 3900W.',
        subcategory: 'ASIC',
        baseCost: 120000,
        baseHashrate: 105000,
        basePower: 3900,
        costMultiplier: 1.5,
        unlocked: false,
        requirement: { totalBTC: 9.0 }
    },
    {
        id: 'antminer_s19xp',
        name: 'Antminer S19 XP',
        description: 'Enthusiast ASIC, 130 TH/s, 3500W.',
        subcategory: 'ASIC',
        baseCost: 180000,
        baseHashrate: 130000,
        basePower: 3500,
        costMultiplier: 1.55,
        unlocked: false,
        requirement: { totalBTC: 12.0, hashPoints: 5 }
    },
    {
        id: 'antminer_s21',
        name: 'Antminer S21',
        description: 'Enthusiast ASIC, 180 TH/s, 4000W.',
        subcategory: 'ASIC',
        baseCost: 220000,
        baseHashrate: 180000,
        basePower: 4000,
        costMultiplier: 1.6,
        unlocked: false,
        requirement: { totalBTC: 15.0, hashPoints: 8 }
    },
    {
        id: 'whatsminer_m60',
        name: 'Whatsminer M60',
        description: 'Enthusiast ASIC, 150 TH/s, 3900W.',
        subcategory: 'ASIC',
        baseCost: 200000,
        baseHashrate: 150000,
        basePower: 3900,
        costMultiplier: 1.58,
        unlocked: false,
        requirement: { totalBTC: 14.0, hashPoints: 7 }
    },
    // --- Specialized/Altcoin ASICs ---
    {
        id: 'antminer_ks3',
        name: 'Antminer KS3 (Kaspa)',
        description: 'Specialized Kaspa ASIC, 8.3 GH/s, 3200W.',
        subcategory: 'ASIC',
        baseCost: 45000,
        baseHashrate: 8300000,
        basePower: 3200,
        costMultiplier: 1.45,
        unlocked: false,
        requirement: { totalBTC: 6.0, hashPoints: 10 }
    },
    {
        id: 'ipollo_v1mini',
        name: 'iPollo V1 Mini (ETH)',
        description: 'ETH ASIC, 300 MH/s, 240W.',
        subcategory: 'ASIC',
        baseCost: 600,
        baseHashrate: 300,
        basePower: 240,
        costMultiplier: 1.18,
        unlocked: false,
        requirement: { totalBTC: 0.12 }
    },
    {
        id: 'goldshell_kd_box_pro',
        name: 'Goldshell KD Box Pro',
        description: 'Kadena ASIC, 2.6 TH/s, 230W.',
        subcategory: 'ASIC',
        baseCost: 1000,
        baseHashrate: 2600,
        basePower: 230,
        costMultiplier: 1.19,
        unlocked: false,
        requirement: { totalBTC: 0.18 }
    },
    {
        id: 'goldshell_hs_lite',
        name: 'Goldshell HS Lite',
        description: 'Handshake/Sia ASIC, 2.9 TH/s, 700W.',
        subcategory: 'ASIC',
        baseCost: 1100,
        baseHashrate: 2900,
        basePower: 700,
        costMultiplier: 1.20,
        unlocked: false,
        requirement: { totalBTC: 0.20 }
    },
    {
        id: 'jasminer_x16q',
        name: 'Jasminer X16-Q (ETH)',
        description: 'ETH ASIC, 1.845 GH/s, 620W.',
        subcategory: 'ASIC',
        baseCost: 2200,
        baseHashrate: 1845,
        basePower: 620,
        costMultiplier: 1.22,
        unlocked: false,
        requirement: { totalBTC: 0.32 }
    },
    {
        id: 'antminer_l7',
        name: 'Bitmain Antminer L7',
        description: 'Litecoin/Doge ASIC, 9.5 GH/s, 3425W.',
        subcategory: 'ASIC',
        baseCost: 22000,
        baseHashrate: 9500,
        basePower: 3425,
        costMultiplier: 1.35,
        unlocked: false,
        requirement: { totalBTC: 5.0 }
    },
    {
        id: 'antminer_dr7',
        name: 'Bitmain Antminer DR7',
        description: 'Decred ASIC, 128 TH/s, 2800W.',
        subcategory: 'ASIC',
        baseCost: 25000,
        baseHashrate: 128000,
        basePower: 2800,
        costMultiplier: 1.4,
        unlocked: false,
        requirement: { totalBTC: 6.5 }
    },
    // Research-unlockable hardware
    {
        id: 'fpga',
        name: 'FPGA Miner',
        description: 'Field-Programmable Gate Array. Flexible and efficient.',
        subcategory: 'Other',
        baseCost: 4000,
        baseHashrate: 5000,
        basePower: 800,
        costMultiplier: 1.19,
        unlocked: false,
        requirement: { researchNode: 'unlock_fpga' }
    },
    {
        id: 'asic_pro',
        name: 'Professional ASIC',
        description: 'High-end commercial mining hardware.',
        subcategory: 'ASIC',
        baseCost: 180000,
        baseHashrate: 200000,
        basePower: 2500,
        costMultiplier: 1.5,
        unlocked: false,
        requirement: { researchNode: 'unlock_asic_pro' }
    },
    {
        id: 'immersion_asic',
        name: 'Immersion-Cooled ASIC',
        description: 'ASICs cooled in dielectric fluid for maximum efficiency.',
        subcategory: 'ASIC',
        baseCost: 300000,
        baseHashrate: 350000,
        basePower: 2000,
        costMultiplier: 1.55,
        unlocked: false,
        requirement: { researchNode: 'unlock_immersion' }
    },
    {
        id: 'photonic',
        name: 'Photonic Quantum Miner',
        description: 'Uses light-based quantum computing for incredible speeds.',
        subcategory: 'Other',
        baseCost: 1200000,
        baseHashrate: 2500000,
        basePower: 8000,
        costMultiplier: 1.6,
        unlocked: false,
        requirement: { researchNode: 'unlock_photonic' }
    },
    {
        id: 'nano_miner',
        name: 'Nanoscale Miner',
        description: 'Molecular-level mining technology.',
        subcategory: 'Other',
        baseCost: 2000000,
        baseHashrate: 5000000,
        basePower: 6000,
        costMultiplier: 1.65,
        unlocked: false,
        requirement: { researchNode: 'unlock_nano' }
    },
    {
        id: 'dimensional',
        name: 'Dimensional Rift Miner',
        description: 'Harnesses computing power from parallel dimensions.',
        subcategory: 'Other',
        baseCost: 10000000,
        baseHashrate: 25000000,
        basePower: 15000,
        costMultiplier: 1.7,
        unlocked: false,
        requirement: { researchNode: 'unlock_dimensional' }
    },
    {
        id: 'reality_proc',
        name: 'Reality-Bending Processor',
        description: 'Manipulates the fabric of reality itself to mine.',
        subcategory: 'Other',
        baseCost: 50000000,
        baseHashrate: 150000000,
        basePower: 25000,
        costMultiplier: 1.8,
        unlocked: false,
        requirement: { researchNode: 'unlock_reality' }
    }
];


